/**
* Application settings
*/
export const FETCH_STATIC_API = 'FETCH_STATIC_API';
export const SIDEBAR_STATE = 'SIDEBAR_STATE';
export const NAVBAR_SELECTED_ITEM = 'NAVBAR_SELECTED_ITEM';

/**
* Static content actions
*/
export const STATIC_EDU_CONTENT = 'STATIC_EDU_CONTENT';
export const STATIC_EXP_CONTENT = 'STATIC_EXP_CONTENT';
export const STATIC_SKILLS_CONTENT = 'STATIC_SKILLS_CONTENT';
export const STATIC_PORTFOLIO_CONTENT = 'STATIC_PORTFOLIO_CONTENT';
